### ISSUE TITLE
Add the ability to create an empty tasks file

### ISSUE THREAD

**Issue by Shatur95** [skywind3000/asynctasks.vim#10]
Hi! Thank you for your plugin.
Currently command `:AsyncTaskEdit` will create an example tasks file if it does not exists. I suggest to add a configuration parameter that will allow to create an empty file in this case. It may be very useful with snippets. For example, I can create snippet for regular CMake project, open tasks file and use my custom template.

**Comment by skywind3000** [comment]
So, an option like `g:asynctasks_template`, set to zero to create empty tasks file ?? And you can be free to use your own template in your ultisnip or something ?

**Comment by skywind3000** [comment]
updated:

    let g:asynctasks_template = 0

**Comment by Shatur95** [comment]
Thank you, just what I need!

**Comment by skywind3000** [comment]
FYI, you can use popular fuzzy finders to choose tasks:

https://github.com/skywind3000/asynctasks.vim/wiki/UI-Integration

![图片](https://user-images.githubusercontent.com/3035071/75658447-5133df00-5ca3-11ea-976c-d5cefdede279.png)

**Comment by Shatur95** [comment]
I didn’t know about it. I decided to try suggested configuration for with FZF, but got an error:
![изображение](https://user-images.githubusercontent.com/22453358/75661849-c0470e80-5c76-11ea-8e20-0293e1dd7a11.png)

**Comment by skywind3000** [comment]
Sorry , `s:lf_task_source()` is a function from leaderf integration. I have removed it now:

Use this:

```
function! s:fzf_task()
	let rows = asynctasks#source(&columns * 48 / 100)
	let source = []
	for row in rows
		let name = row[0]
		let source += [name . '  ' . row[1] . '  : ' . row[2]]
	endfor
	let opts = { 'source': source, 'sink': function('s:fzf_sink'),
				\ 'options': '+m --nth 1 --inline-info --tac' }
	if exists('g:fzf_layout')
		for key in keys(g:fzf_layout)
			let opts[key] = deepcopy(g:fzf_layout[key])
		endfor
	endif
	call fzf#run(opts)
endfunction
```

**Comment by Shatur95** [comment]
Thanks, it works now. But fzf opens full screen, but on the screenshot it in the center. How did you do that?

**Comment by skywind3000** [comment]
let g:fzf_layout={'window': {'width':0.9, 'height':0.6}}

it soppurts popup/floatwin

**Comment by Shatur95** [comment]
Thanks!

**Comment by roachsinai** [comment]
[Task with different profiles](https://github.com/skywind3000/asynctasks.vim/blob/master/README.md#task-with-different-profiles)

Is there a way let leaderf support `task with different profiles`?

If I have a setting:

```
[task1:release]
command=gcc -O2 "$(VIM_FILEPATH)" -o "$(VIM_PATHNOEXT)"
cwd=$(VIM_FILEDIR)

[task1:debug]
...
```

use setting [UI Integration · skywind3000/asynctasks.vim Wiki](https://github.com/skywind3000/asynctasks.vim/wiki/UI-Integration) will only show `task1`(and run command same as debug), so I can't run `task1:release`.

And seems to make it should add an argument of all involved functions like:`asynctasks#source` and `asynctasks#list` is there a smart way to make it?

**Comment by skywind3000** [comment]
@roachsinai , change the current profile by:

```vimL
:let g:asynctasks_profile = 'release'
```

**Comment by caoshenghui** [comment]
https://github.com/skywind3000/asynctasks.vim/wiki/UI-Integration

我在使用leaderf配置时候会报错，原因似乎是`\ 'help' : 'navigate available tasks from asynctasks.vim',`这一行放在了高亮里面。放外面就没问题了

作者可以尝试看看。

**Comment by skywind3000** [comment]
果然，已修正，多谢
