### ISSUE TITLE
Multiline command

### ISSUE THREAD

**Issue by szsam** [skywind3000/asynctasks.vim#100]
Is it possible to write a multiline command? E.g.
``` ini
[file-build]
command=gcc -O2 "$(VIM_FILEPATH)" -o "$(VIM_FILEDIR)/$(VIM_FILENOEXT)" \
    -Wall -Wextra \
    -I/some/very/long/dir1 \
    -I/some/very/long/dir2
cwd=$(VIM_FILEDIR)
```

**Comment by skywind3000** [comment]
Sorry, multiline command is hard to implement right now,
plus that `\` is a line-continue mark in unix but it is a valid root path in windows. it is ambiguous.

**Comment by szsam** [comment]
Thanks. I'll try writing a shell script.
