### ISSUE TITLE
Macro variables referenced in the [+] section are not expanded when running tasks right in shell

### ISSUE THREAD

**Issue by szsam** [skywind3000/asynctasks.vim#101]
The `.tasks` file:
``` ini
[+]
VAR=<root>

[project-build]
command=ls -d "$(+VAR)"
#command=ls -d "<root>"
cwd=<root>
```

In bash,
``` sh
$ tree . -a
.
├── .root
└── .tasks

0 directories, 2 files

$ asynctask project-build
ls: cannot access '<root>': No such file or directory
```

However, if we run the task in vim, the macro is expanded as expected:
![20221109164229](https://user-images.githubusercontent.com/20792991/200948050-ded85769-bc12-4776-943c-670bf1157d35.jpg)

**Comment by skywind3000** [comment]
this is an order issue, 
in the python script, macros are expanded before internal variables.

fixed in: https://github.com/skywind3000/asynctasks.vim/commit/9053c97fc77ac3335761527d4431f936631e3a24

please update to the latest version and try again.

**Comment by szsam** [comment]
Thanks!
