### ISSUE TITLE
Make $(VIM_FILEDIR) valid in nofile buffer

### ISSUE THREAD

**Issue by voldikss** [skywind3000/asynctasks.vim#11]
https://github.com/skywind3000/asynctasks.vim/blob/3c68c42a04a75e8e4e1a9862e94f8d594472f209/plugin/asynctasks.vim#L936-L951

# 问题：

打开一个 `buftype` 为 `'nofile'` 的 buffer，如果执行的命令里面带有 `$(VIM_FILEDIR)`，会报错 `Warning: macro $(VIM_FILEDIR) is empty in current buffer`.

# 原因

对于 `buftype` 为 `'nofile'` 的 buffer, `expand("%:p")` 为空字符串，但是 `expand("%:p:h")` 却返回该缓冲区所在的文件夹路径且不为空，并且在同样的 buffer 里面， `$(VIM_FILEDIR)` 这个宏在 [asyncrun.vim](https://github.com/skywind3000/asyncrun.vim/blob/a7ebec5f5097c46a3ee4503d8c9bfb989a8ff773/plugin/asyncrun.vim#L1567) 里也工作正常。

因此可不可以将 `$(VIM_FILEDIR)` 排除在 `disable` 之外呢？

**Comment by skywind3000** [comment]
只是 asyncrun 没有做这个检测，就有人用错过，这个东西我想过，`nofile` 的 buffer 居然有 FILEDIR，道理上说不通，而你在 nofile 的 buffer 里运行 `echo expand("%:p")` 其实显示的是 Vim 的当前目录 `:pwd` 返回那个，并不是真正意义上的 file dir，既然如此你就用 `$(VIM_CWD)` 就行了嘛。

**Comment by voldikss** [comment]
OK, 已用 $(VIM_CWD) 代替了

**Comment by skywind3000** [comment]
恩，有一天vim可能真的要靠cd 路径来模拟vscode的open folder 做项目管理这事情。
