### ISSUE TITLE
multi runner support?

### ISSUE THREAD

**Issue by Rose1917** [skywind3000/asynctasks.vim#118]
I want to get a runner for each buffer. For example, I want to run a `tail /bin/log.txt | grep FILENAME` command for each tab's file, and I want when I change to each tab, I want see the grep results for that buffer. Can this be realized by now?
I know that there is a reuse option, but when I call asynctaskrun file-grep on another tab, it reports background is still running.

![image](https://github.com/user-attachments/assets/ff1a417f-8c4c-4663-97a4-329802ee1b1c)

**Comment by Rose1917** [comment]
Just use pos=botttom solved this.

**Comment by skywind3000** [comment]
I prefer `pos=TAB`
