### ISSUE TITLE
Define custom variables

### ISSUE THREAD

**Issue by Shatur95** [skywind3000/asynctasks.vim#12]
Is it possible to add the ability to define custom variables? For example, I have the following two tasks:
```ini
[project-build]
command=cmake --build . --target myawesomprogram
cwd=<root>/../build-$(VIM_PRONAME)-debug
errorformat=%f:%m:%l

[project-run]
command=myawesomprogram --argument example
cwd=<root>/../build-$(VIM_PRONAME)-debug
output=terminal
```
The first task builds the selected application from the entire project, and the second starts this application. If you need to change the application, then I need to replace its occurrences. It would be convenient to be able to set custom variable at the begging of the file for it.

Alternatively, this variable can be built-in and set from cmd like a profile.

**Comment by skywind3000** [comment]
1. system environment variable is capable for this:

    command=echo $HOME

And thay can be changed in vimscript:

    let $HOME = 'somewhere'

2. There is also internal variable:

https://github.com/skywind3000/asynctasks.vim/wiki/Task-Examples#internal-variable-example

**Comment by Shatur95** [comment]
Yes, this will work, but such settings allows set the name system-wide, while executable file is project-wide. Is it possible to set this variable only for specific project?

**Comment by skywind3000** [comment]
Currently, still want to keep this plugin simple enough
and no plan for project-wide variables.

**Comment by Shatur95** [comment]
Okay, It's not a problem to replace several occurrences, especially in vim :)
