### ISSUE TITLE
Add the ability to skip :AsyncTaskEdit confirmation

### ISSUE THREAD

**Issue by Shatur95** [skywind3000/asynctasks.vim#15]
When executing the command `:AsyncTaskEdit` is proposed to confirm the path to the file with tasks with the possibility of changing it. Could you add an option to bypass this confirmation and always open the file?

**Comment by skywind3000** [comment]
updated: https://github.com/skywind3000/asynctasks.vim/commit/97b55f5a9d9a319c8d04290dd1bcceece85f9a3f

**Comment by Shatur95** [comment]
You are super fast, thank you!
