### ISSUE TITLE
:AsyncTasksEdit allows to open split several times

### ISSUE THREAD

**Issue by Shatur95** [skywind3000/asynctasks.vim#18]
If I execute `:AsyncTasksEdit` it will open configuration in split. But If I execute this command More than once - I will have another splits of the same window:
[![asciicast](https://asciinema.org/a/Vy5HRZzN4wGqvCU32MII1kTkR.svg)](https://asciinema.org/a/Vy5HRZzN4wGqvCU32MII1kTkR)

Is this expected behavior? As for me it would be nice to just focus previously opened configuration split (as in [figitive](https://github.com/tpope/vim-fugitive)) or toggle it.

**Comment by skywind3000** [comment]
updated

**Comment by Shatur95** [comment]
Thank you!
