### ISSUE TITLE
:AsyncTaskEdit not respect :vert

### ISSUE THREAD

**Issue by Shatur95** [skywind3000/asynctasks.vim#19]
If I use `:vert AsyncTaskEdit` it still opens horizontal split. Is it possible to change this behavior? For example, fugitive allows to pass `:vert` to `G` command. Or maybe add an option where to open configuration buffer?

**Comment by skywind3000** [comment]
updated: https://github.com/skywind3000/asynctasks.vim/commit/a37ae4eba2e95f896c09e4aac3c2ffbc21f35920

**Comment by Shatur95** [comment]
Thank you!
