### ISSUE TITLE
能否为不同的task提供不同的terminal打开位置的选项

### ISSUE THREAD

**Issue by ZhiyuanLck** [skywind3000/asynctasks.vim#2]
在配置文件中添加output=terminal后能否继续设置pos选项指定terminal打开位置

**Comment by skywind3000** [comment]
可以的，有这个选项的 就叫 pos

**Comment by skywind3000** [comment]
嗯，检查了一下，之前的版本还没有 `pos=?` ，刚刚添加了：

https://github.com/skywind3000/asynctasks.vim/commit/b526df601279ee46d2918d691247ad410f0b7d3f
