### ISSUE TITLE
WIKI Command-Line-Tool Usage TYPO

### ISSUE THREAD

**Issue by nickChenyx** [skywind3000/asynctasks.vim#22]
[Command-Line-Tool#Usage](https://github.com/skywind3000/asynctasks.vim/wiki/Command-Line-Tool#usage)

> You don't have to jump back to your project root manually, because `profile-build` has a cwd=`<root>`.

`profile-build`  should be `project-build`.

AND

`asynctask -profile=release project-build` notice `-profile=release` setting, but no more description, when and where `release` take effect?

**Comment by nickChenyx** [comment]
😂 README description is more detailed. [profile here](https://github.com/skywind3000/asynctasks.vim#task-with-different-profiles)

**Comment by skywind3000** [comment]
thanks, `profile` in the readme file is a feature not a typo.
