### ISSUE TITLE
Are there any willings to support specifying default value for `$(?prompt)`

### ISSUE THREAD

**Issue by lukmy** [skywind3000/asynctasks.vim#23]
e.g. `$(?prompt:-default value)` or `$(?prompt:=default value)`

**Comment by skywind3000** [comment]
updated: https://github.com/skywind3000/asynctasks.vim/commit/a13a4f31146d154625073039f83a16e845c72301

use `$(?prompt:default value)` to provide a default value, and `$(?prompt:)` to remember last input history

**Comment by lukmy** [comment]
thanks :)

**Comment by roachsinai** [comment]
Could $(?prompt:default value) avaliable for [你最常用的一个 linux 命令是什么？为什么？ - 韦易笑的回答 - 知乎](https://www.zhihu.com/question/20620445/answer/1063450249)?
