### ISSUE TITLE
[request] autocmd support for tasks

### ISSUE THREAD

**Issue by barney-s** [skywind3000/asynctasks.vim#24]
Working on a rust project, I am setting up:

autocmd BufWritePost * AsyncTask cargo-run

This is perfect to compile and run tiny programs every time I edit the file. 
But I cannot set this in global .vimrc since this would be run for all files immaterial of the project (cwd).

Would it be possible to support auto triggering of AsyncTasks on BufWritePost events ?

I considered using localvimrc plugin to inject autocmds.
But that would be another file I need to maintain.
https://www.vim.org/scripts/script.php?script_id=3393

**Comment by barney-s** [comment]
Also may be support this too.
This would trigger AsyncRun always but will be ignored for non-rust files.
Today it errors.

```
[task]
command=
command:rust=cargo run .
output=terminal
```

**Comment by skywind3000** [comment]
try this:

    autocmd BufWritePost rust AsyncTask cargo-run

**Comment by barney-s** [comment]
This worked:
```
autocmd BufWritePost *.rs AsyncTask cargo-run
```

**Comment by skywind3000** [comment]
OK
