### ISSUE TITLE
Run detached tasks

### ISSUE THREAD

**Issue by Shatur95** [skywind3000/asynctasks.vim#25]
I made the following global tasks:
```ini
[project-open-build]
command=xdg-open $(VIM_ROOT)/../build-$(VIM_PRONAME)-$(VIM_PROFILE)
silent=1

[project-open-source]
command=xdg-open $(VIM_ROOT)
silent=1
```
It allow me to quickly open build and source folders. But if I am running compilation or a compiled program, then I can not use the above tasks. Is it possible to just run such tasks without any callbacks and output even if the main task is currently running? Something like `save=2` but `silent=2`.

**Comment by skywind3000** [comment]
yes, try this:

```ini
[project-open-build]
command=xdg-open $(VIM_ROOT)/../build-$(VIM_PRONAME)-$(VIM_PROFILE)
output=hide
```

**Comment by Shatur95** [comment]
But it shows me the following if another task is running (building, for example):
![изображение](https://user-images.githubusercontent.com/22453358/77474353-a042df00-6e1f-11ea-9dc1-4b8a3715adb3.png)

**Comment by skywind3000** [comment]
update and try again:

    output=hide

**Comment by Shatur95** [comment]
Thank you!
