### ISSUE TITLE
CLITool Error: not find asynctask.py 

### ISSUE THREAD

**Issue by LilithBristol** [skywind3000/asynctasks.vim#28]
Ubuntu 18.04LTS

Error: not find asynctask.py
这个怎么解决啊？谢谢

我的 asynctasj.vim 放在 /home/myname/ 下面
按照作者大大的文档  把 /home/myname/asynctask.vim/bin/asynctask 
软链接到 /usr/myname/bin下面
然后 把/usr/myname/bin 加入到用户的 .bashrc的PATH里
`export PATH=~/bin:$PATH `

这时候 在 /home/myname/bin 执行task 一切正常
但是在 /目录执行就报错了
**Error: not find asynctask.py**

尝试了以下解决方案 都不行

在 /home/myname/bin 目录增加了一个软链接 asynctask.py 连接到/home/myname/asynctask.vim/bin/asynctask.py 
同样报错

把整个asynctask.vim全部复制到 /home/myname/bin目录
同样报错

在 /etc/profile 增加配置
`export PATH=~/bin:$PATH `
使用 $PATH命令 是可以看到PATH目录包含 /home/myname/bin的
但是在 /目录 执行task 还是报错
**Error: not find asynctask.py**

在 /home/myname/bin 目录就可以正确执行

**Comment by againxx** [comment]
I cannot reproduce it in my computer.

![asynctask_cli](https://user-images.githubusercontent.com/22728604/82230963-0864fb80-995f-11ea-8c01-981882219c24.png)

**Comment by LilithBristol** [comment]
在ubuntu centos两种操作系统的主机上试了下都有这个问题

懒得找原因了 把 asynctask.py每个系统path下都复制了一副 这么用吧

**Comment by againxx** [comment]
You can try to `echo $SCRIPTPATH` to check whether it contains the directory of asyntask.py
In my ubuntu18.04, it prints the corrent path in  `asyntasks.vim/bin`.

![asynctask_cli2](https://user-images.githubusercontent.com/22728604/82235990-08b4c500-9966-11ea-95af-238c94e104c7.png)
![asynctask_cli3](https://user-images.githubusercontent.com/22728604/82236024-179b7780-9966-11ea-8fdc-a64a69592a82.png)

**Comment by LilithBristol** [comment]
试了下 强制指定  $SCRIPTPATH为固定目录 可以使用 谢谢
