### ISSUE TITLE
confusion about output=terminal

### ISSUE THREAD

**Issue by andymass** [skywind3000/asynctasks.vim#32]
In vim `8.2.814` on linux, using `output=terminal` in the `.tasks` file doesn't seem to do anything special- the output still goes to the quickfix, as viewed with `:copen`.  However, if I add `pos=bottom` it _does_ open a `:terminal`as expected.  It is not a big deal, but I am a bit confused about the meaning of the terminal option when `pos` is not specified.  Is this the expected behavior? 

```
[project-build]
command=cmake --build build
cwd=<root>
output=terminal
# pos=bottom         # without uncommenting this line, no terminal opens
errorformat=%f:%l:%m
```

**Comment by skywind3000** [comment]
The default position should be initialized via `g:asynctasks_term_pos`:

```VimL
let g:asynctasks_term_pos = 'tab'
```

**Comment by andymass** [comment]
OK, thanks!  I will make sure to do that.  It was just a little surprising to me that `output=terminal` doesn't do anything by default.

**Comment by skywind3000** [comment]
It is documented [here](https://github.com/skywind3000/asynctasks.vim#task-running-modes).

![图片](https://user-images.githubusercontent.com/3035071/87187883-79ea7600-c320-11ea-893d-22f2a3c47361.png)

**Comment by andymass** [comment]
I understand now.  Thank you!
