### ISSUE TITLE
Feature request: Dropdown when asking for user input

### ISSUE THREAD

**Issue by hnspn** [skywind3000/asynctasks.vim#38]
Any way to get a dropdown when asking for user input?

```
[task1]  
command=echo hello $(?your name), you are a $(?gender[male,female]).  
output=terminal
```

Not sure if we can use the default vim autocomplete or we would expose a way to use fzf.

**Comment by roachsinai** [comment]
@hnspn check #46 , wish it works.

**Comment by skywind3000** [comment]
@roachsinai and @hnspn , I reimplement this in the latest version: 1.8.1

syntax:

```ini
[test]
command=echo Your gender is $(?gender:&male,&female) !
```

It uses `confirm()`, to select multiple candidates:

![图片](https://user-images.githubusercontent.com/3035071/103303891-1a089880-4a42-11eb-9e92-81b7bc7dcc53.png)

in GVim, `confirm()` will display a GUI dialog:

![图片](https://user-images.githubusercontent.com/3035071/103303945-48867380-4a42-11eb-8af3-d509e3ac4a45.png)

And this plugin will remember your last input as the default one.

and

**Comment by roachsinai** [comment]
Very great help!

**Comment by hnspn** [comment]
thanks
