### ISSUE TITLE
Change local task file location

### ISSUE THREAD

**Issue by hnspn** [skywind3000/asynctasks.vim#39]
I would like to have the option to change the locatio nof the local .task file.
personaly I would like to put it in `$(VIM_ROOT)/.vim/tasks.json`  

In the same place as the local coc config file.

maybe add an option like this.

`let g:asynctasks_local_tasks_config_prefix='.vim'`

**Comment by skywind3000** [comment]
let g:asynctasks_config_name = '.vim/task.json'

**Comment by hnspn** [comment]
Thanks
