### ISSUE TITLE
[error] Get an error when a command contains setting environment variable which has 'VERSION' as part of its name

### ISSUE THREAD

**Issue by Irving-cl** [skywind3000/asynctasks.vim#40]
If I set such a command in `tasks.ini`:
```
[hi]
command=MY_VERSION=1.2 echo hello
```
When I execute it in asynctask, I would get such an error:
```
Error: $(VIM_VERSION) is invalid in command line
from /XXX/XXX/.config/asynctask/tasks.ini:
command=MY_VERSION=1.2 echo hello
```
I've verified that so long as the variable's name contains 'VERSION' it would have this problem.
It seems that this env variable breaks `VIM_VERSION`, but they don't have the same name. Is there any fix for this?

**Comment by skywind3000** [comment]
![图片](https://user-images.githubusercontent.com/3035071/87119771-7d92e400-c2b1-11ea-8cf6-16f2cd71d2fe.png)

I can't reproduce your problem

**Comment by skywind3000** [comment]
Overrided by another task with same name ?

**Comment by Irving-cl** [comment]
I think I don't have another task. I haven't tried it in vim, I did it in a shell, could you please try this in a shell:
```
asynctask -f
(Then choose hi and execute it)
```

**Comment by skywind3000** [comment]
fixed

**Comment by Irving-cl** [comment]
Thanks!
