### ISSUE TITLE
Config the default position and height of quickfix window

### ISSUE THREAD

**Issue by chrisniael** [skywind3000/asynctasks.vim#48]
Is there a way to configure the default **position** and **height** of the **quickfix window**?

**Terminal window** can be configured like this:

```
output=terminal
pos=top
rows=10
```

But, what can I do for **quickfix window**?

**Comment by skywind3000** [comment]
let g:asyncrun_open = 6

**Comment by chrisniael** [comment]
@skywind3000 Thanks reply.
How about the **position** of quickfix window. If I want config quickfix window display on the **top** by default.

**Comment by skywind3000** [comment]
maybe you can open the quickfix window as you like before calling asynctasks

**Comment by chrisniael** [comment]
Well, hope someone has time to implement this feature.
