### ISSUE TITLE
How to use cwd setting?

### ISSUE THREAD

**Issue by benallan** [skywind3000/asynctasks.vim#5]
Regardless of what I set for `cwd` under a file-run task, it seems like the task always runs with the current vim directory (not the cwd I set). 

Here's my .tasks file, located in the project root (next to the .git folder):
```
[file-run]
command=make test
# working directory
cwd="$(VIM_FILEDIR)/.."
output=terminal
```

Here's the project structure:
```
root
├── .tasks
└── c
    └── hello-world
        ├── README.md
        ├── makefile
        ├── src
        │   ├── hello_world.c
        │   └── hello_world.h
        ├── test
        │   └── test_hello_world.c
        └──── tests.out
```

If I launch vim in the hello-world dir, then run the file-run task, it works fine (correctly calling make with the makefile). But if I launch vim in any other directory, it fails, as make cannot find the makefile. 

I also tried using an absolute path for cwd, but it didn't work either. As a workaround, this is what I'm doing now:
```
command=cd "$(VIM_FILEDIR)/.." && make test
````

How can I set the cwd to be used for the command? I tried searching the  codebase for opt.cwd, but couldn't find where it was used, so I'd be grateful if you had any ideas.

AsyncTasks seems like a really useful plugin, thanks for all your work on it!

**Comment by skywind3000** [comment]
don‘t quote in zhe cwd

**Comment by benallan** [comment]
Great, thanks!

```
cwd=$(VIM_FILEDIR)/..
```
