### ISSUE TITLE
能不能支持下多个asynctasks_config_name?

### ISSUE THREAD

**Issue by fcying** [skywind3000/asynctasks.vim#51]
一个名字里面搜索到配置文件后就可以不管别的名字了. 
方便不同项目tasks放在不同的位置里. (自己的放.tasks, 别的不能改的项目放.git 或者.svn里)
```
let asynctasks_config_name= [
    \ '.tasks',
    \ '.root/.tasks',
    \ '.git/.tasks',
    \ '.svn/.tasks',
    \ ]
```

**Comment by skywind3000** [comment]
已经实现了：https://github.com/skywind3000/asynctasks.vim/commit/bfbde0b5b0dbd10b78d3438544ea4f4b99faca0f 和 https://github.com/skywind3000/asynctasks.vim/commit/1fafc31c7b12cd2e09ccdd446286b5255a9937d3
