### ISSUE TITLE
asynctasks_term_pos = 'external' is the same as 'vim'

### ISSUE THREAD

**Issue by Filip62** [skywind3000/asynctasks.vim#54]
Arch Linux
Neovim 0.5.0

`asynctasks_term_pos = 'external'` does not open external terminal, instead it runs the same as `asynctasks_term_pos = 'vim'`

Task:
```ini
[file-run]
command=fish "$(VIM_FILENAME)"
cwd=$(VIM_FILEDIR)
output=terminal
save=1
```

Async settings:
```viml
let g:asyncrun_open = 6
let g:asynctasks_term_pos = 'external'
```

**Comment by skywind3000** [comment]
`external` is only supported on windows. but you can achieve same thing by customizing runners:

https://github.com/skywind3000/asynctasks.vim/wiki/Customize-Runner

**Comment by Filip62** [comment]
Wow, that's awesome.
