### ISSUE TITLE
FAQ page has syntax error

### ISSUE THREAD

**Issue by yolo2h** [skywind3000/asynctasks.vim#56]
<https://github.com/skywind3000/asynctasks.vim/wiki/FAQ>

The sample code is missing a comma

> Plug 'skywind3000/asyncrun.vim' {'on': ['AsyncRun', 'AsyncStop'] }
> Plug 'skywind3000/asynctasks.vim' {'on': ['AsyncTask', 'AsyncTaskMacro', 'AsyncTaskList', 'AsyncTaskEdit'] }

pop `E116: Invalid arguments for function plug#` when start vim.

**Comment by skywind3000** [comment]
fixed, thanks
