### ISSUE TITLE
win7下tasks.ini全局配置不起作用，必须文件名是.tasks才能起作用

### ISSUE THREAD

**Issue by yllr78** [skywind3000/asynctasks.vim#57]
windows7系统，tasks.ini和_vimrc在同一目录，目录结构如下：

D:\Program Files (x86)\Vim
|------_vimrc
|------tasks.ini
|------vimfiles
|------vim82（vim程序目录）----gvim.exe

文件名是tasks.ini时完全不起作用，改成.tasks只有VIM目录起作用，VIM以外的其他目录均不起作用。

请大神看看是什么原因，谢谢！

**Comment by yllr78** [comment]
自己解决了，tasks.ini文件必须要放到vimfiles目录下才能起作用，linux下就是要放在.vim目录下。感谢作者的辛苦付出。

**Comment by skywind3000** [comment]
不用放到 vimfiles 里面，全局 tasks.ini 文件放在

    c:\users\username\.vim

或者：

    /home/username/.vim

下面即可，不用污染 vim 的文件夹。
