### ISSUE TITLE
链接一个任务名到另一个任务

### ISSUE THREAD

**Issue by mzr1996** [skywind3000/asynctasks.vim#58]
在开发的时候，我经常会需要在一段时间执行某一个task，并在不同时间进行任务切换。
因此我希望定义一系列任务，并设置一个默认的任务，比如说[run]，并将这个任务与vim的快捷键绑定。切换任务时，只需要修改[run]链接到的任务即可，类似如下的配置：
```
[run]
link=train-peta

[train-peta]
command=python "tools/train.py" "configs/peta.yaml"
cwd=$(VIM_ROOT)
output=terminal
save=1

[train-wider]
command=python "tools/train.py" "configs/wider.yaml"
cwd=$(VIM_ROOT)
output=terminal
```
请问能否实现？

**Comment by skywind3000** [comment]
这个非常麻烦，你可以换种配置法：

```
[run]
command=python ...  && python ...
```

用 && 链接你的两条命令。

**Comment by mzr1996** [comment]
> 这个非常麻烦，你可以换种配置法：
> 
> ```
> [run]
> command=python ...  && python ...
> ```
> 
> 用 && 链接你的两条命令。

并不是希望链接两个命令，而是类似重定向的意思。执行run的时候自动根据`link`项跳转到对应的task

**Comment by mzr1996** [comment]
我自己尝试了一下，在`asynctasks#start`函数中加入这样一段（1163行），基本就实现了目标功能（不过不清楚会不会引入bug），希望能作为参考？
```
  let source = 'task ['. a:taskname . '] from ' . ininame
  " ----- 开始 ------
  let link = get(task, 'link', '')
  if link != ''
    if (a:0 < 3) || (a:0 >= 3 && a:1 <= 0)
      call asynctasks#start(a:bang, link, path)
    else
      call asynctasks#start(a:bang, link, path, a:1, a:2, a:3)
    endif
    return 0
  endif
  " ----- 结束 -----
  let command = s:command_select(task, &ft)
```

**Comment by skywind3000** [comment]
这样的话，这个功能早就有了，asynctasks 有两种方法实现你的需求：

方法1：环境变量替换

```
[my-task]
command=echo $(VIM:hello)
```

然后在字典 `g:asynctasks_environ` 中设定 hello 的值：

```
let g:asynctasks_environ['hello'] = 'world'
```

然后 `:AsyncTask my-task` 运行的时候，就会把 `$(VIM:hello)` 替换成字典中 hello 对应的字符串。

方法二：使用 profile (编译配置)

传统对同一个编译目标，都有 debug, release 等多项不同的配置，那么对于同一个任务也可以设置多种配置对应的不同命令：

```
[task1:release]
command=gcc -O2 "$(VIM_FILEPATH)" -o "$(VIM_PATHNOEXT)"
cwd=$(VIM_FILEDIR)

[task1:debug]
command=gcc -g "$(VIM_FILEPATH)" -o "$(VIM_PATHNOEXT)"
cwd=$(VIM_FILEDIR)
```

然后你可以用：

    :AsyncTaskProfile {配置名}

来修改当前配置，比如 `:AsyncTaskProfile debug` 切换当前配置为 `debug`，`:AsyncTaskProfile release` 切换为 release，当然配置名字完全是你自己定的，不局限于 `release` 和 `debug`，你直接在任务名字后面冒号配置名就行了。

切换的时候还可以：

    :AsyncTaskProfile release debug test

就是后面跟随多个参数的话，会弹出 GUI 对话框，让你选择切换：

![图片](https://user-images.githubusercontent.com/3035071/109608638-205fe180-7b65-11eb-86f8-03a9d0e4c705.png)

然后 `:AsyncTaskProfile` 不带参数的话，会显示当前的配置。

**Comment by mzr1996** [comment]
这两个方法我确实是知道的，只是和我希望的稍有一些出入。准确的说，我希望的是针对每一个项目，设定某一个任务为当前的默认任务，且这一默认任务是可以切换的。
对于方法一，如果我手动执行let语句，则在每次打开vim时都需要重新执行；如果我写在vimrc中，则切换任务需要修改vimrc并执行，且无法针对不同项目执行不同任务。
方法二需要我将所有的任务都命名为run:a, run:b, run:c ....，然后将快捷键绑定给run任务，虽然有些不直观，倒也可用。但这种方法同样的，在重新打开vim之后就失效了，需要重新指定profile，否则会重置为debug。修改vimrc面临的问题和方法一是一样的

**Comment by skywind3000** [comment]
你说的这个很难实现，但是我扩展了一下内部变量，可以写在任务配置的 `[*]` 区域：

https://github.com/skywind3000/asynctasks.vim/blob/master/README-cn.md#%E5%86%85%E9%83%A8%E5%8F%98%E9%87%8F

**Comment by mzr1996** [comment]
> 
> 
> 你说的这个很难实现，但是我扩展了一下内部变量，可以写在任务配置的 `[*]` 区域：
> 
> https://github.com/skywind3000/asynctasks.vim/blob/master/README-cn.md#%E5%86%85%E9%83%A8%E5%8F%98%E9%87%8F

ok，这样也不错，感觉扩展性更好，多谢啦

**Comment by skywind3000** [comment]
不好意思，为了更好的使用这个 “内部变量”，我做了一个不兼容的重构，原来的 `[*]` 定义区间被改为 `[+]` 区间，因为 `[*]` 后面将会被用于支持通用全局配置，这个名字更直观点，而原来变量名从 `$(VIM:varname)` 改为 `$(+varname)`，详细见：

https://github.com/skywind3000/asynctasks.vim#internal-variables

同时支持在命令后面加参数提供变量定义，比如：

```ini
[greeting]
command=echo Hi, $(-name)
```

可以无需提供变量定义，直接：

```VimL
:AsyncTask greeting  +name=skywind3000
```

当然你也可以定义在前面，然后命令参数后面用加号定义的话，会覆盖配置文件里的 `[+]` 定义的东西。

最后，还可以有默认值，比如：

```ini
[greeting]
command=echo Hi, $(-name:my friend)
```

这样如果配置里的 `[+]` 部分，和命令行后面都没有提供变量 `name` 的定义时，冒号后面的默认值就会启用。
