### ISSUE TITLE
CWD subdirectory ignored

### ISSUE THREAD

**Issue by alexcocinda** [skywind3000/asynctasks.vim#59]
I am using the following config:

```
[debugging]
command=pwd && ls -a
cwd=$(VIM_ROOT)/debug
output=terminal
```

Unless the `debug` folder contains a `Makefile`, `pwd` prints the project root directory. Is this the desired behaviour? Thank you!

**Comment by skywind3000** [comment]
I can't reproduce your problem,

**Comment by alexcocinda** [comment]
Ok so, apparently rebooting fixed the issue. I'm not able to reproduce it anymore. I apologize for wasting your time and thank you for your help. Keep up the good work!
