### ISSUE TITLE
windows下无法识别路径？

### ISSUE THREAD

**Issue by nmxiao** [skywind3000/asynctasks.vim#6]
在windows下用neovim，用户名中有空格时，无法识别路径？报错如下：

'C:\Users\XXX' 不是内部或外部命令，也不是可运行的程序
或批处理文件。用户文件夹为XXX XX

**Comment by skywind3000** [comment]
用的命令是什么？

**Comment by skywind3000** [comment]
怎么定义的

**Comment by nmxiao** [comment]
我自己写的bat，里面的具体内容为
@echo off
@cd /d %~dp1
call "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\bin\compilervars.bat" intel64
icl %1

**Comment by skywind3000** [comment]
定位到了，neovim 在 windows 下面的问题，我传给 jobstart 的 args 是一个列表，列表的话 args 每个项目都应该是一个独立的参数，结果 nvim 它没做好，把一个 args[n] 的项目弄成了，vim没问题，linux下也没问题。我 escape 了都有问题。

**Comment by skywind3000** [comment]
你查 ":h jobstart" 下面有一段 “NOTE: on Windows ..."，实际上我按照它的做了，把包含空格的参数在 windows 下 quote 起来了，还是失败。vim 没问题，linux 下都没问题，我再看看。

**Comment by nmxiao** [comment]
好的，我直觉应该是neovim的问题。以前用在vim下用asyncrun没啥问题。这个插件对我这种多种语言下的快速编译测试还是很有帮助的，多谢！

**Comment by skywind3000** [comment]
可以了，已经修正，专门针对 neovim+windows 换了一种传参方式，麻烦试试。

**Comment by skywind3000** [comment]
更新下 asyncrun.vim 即可，那边已经修正，

neomake 现在 nvim+windows 都有问题：

![图片](https://user-images.githubusercontent.com/3035071/74600252-8cda8080-50c9-11ea-8dd3-4682136b4912.png)

现在 asyncrun 完美传参了：

![图片](https://user-images.githubusercontent.com/3035071/74600256-9b289c80-50c9-11ea-8c0e-128c0b0cfab3.png)

**Comment by nmxiao** [comment]
quickfix下问题解决了。asynctask下用terminal好像还出现这个问题，terminal用的是cmd。

**Comment by skywind3000** [comment]
啥意思？啥叫用的是 cmd ？？

**Comment by skywind3000** [comment]
一并解决了，完美传参了，这回，主要是 windows 下面用户名包含空格 + neovim 实在太少见。
麻烦帮确认下，更新 asyncrun.vim 即可

**Comment by nmxiao** [comment]
搞定了，quickfix和terminal两种模式都OK，多谢！
