### ISSUE TITLE
Conflict with vim-rooter

### ISSUE THREAD

**Issue by LLDay** [skywind3000/asynctasks.vim#61]
File tree:
```sh                                           
[~/project]$ tree -a                                                     
.
├── .root
├── subdir
│   └── somefile.txt
└── .tasks.ini

1 directory, 3 files
```

.tasks.ini
```ini
[pwd-terminal]
command=pwd
cwd=/home/user/project/subdir
output=terminal

[pwd-quickfix]
command=pwd
cwd=/home/user/project/subdir
output=quickfix
```

The task `pwd-terminal` outputs `/home/user/project`, the task `pwd-quickfix` outputs `/home/user/project/subdir`. Cwd with the  $(VIM_ROOT) macro behaves similarly.
I found out that the [vim-rooter](https://github.com/airblade/vim-rooter) plugin causes this behavior. When I turn this plugin off `pwd-terminal` task starts printing the correct path `/home/user/project/subdir`. Correct behavior also happens when I remove .root file because of different pattern settings:
```vim
let g:asynctasks_config_name = '.tasks.ini'
let g:asyncrun_rootmarks = ['.tasks.ini', '.root']
let g:rooter_patterns = ['.root']
```
`:echo asyncrun#get_root('%')` prints `/home/user/project`

Arch Linux 5.11.9
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

**Comment by skywind3000** [comment]
Thanks for reporting this, fixed in asyncrun: https://github.com/skywind3000/asyncrun.vim/commit/0ca4baec21998083220c6030afba5e116e3be9c4

**Comment by LLDay** [comment]
Thank you! It works now
