### ISSUE TITLE
错误跳转失败

### ISSUE THREAD

**Issue by niuiic** [skywind3000/asynctasks.vim#63]
`.tasks`

```
[file-build]
command=make all
cwd=$(VIM_ROOT)
output=quickfix
errorformat=%f:%l:%m
save=1
```

跳转到的文件是空白的。目录结构如下。

语言为rust。VIM_ROOT是A目录。A是workspace。
A下有B和C，C为lib，B为bin。
.task在A下。

编辑B下的main.rs，执行命令，弹出quickfix窗口。跳转错误时错误位于C的文件中，打开的文件为空白文件，没有任何内容。quickfix窗口中显示的文件路径完整，打开的空白文件路径正确，但是进行保存时显示无该文件。

![image](https://user-images.githubusercontent.com/63799565/112919757-4663ac00-913a-11eb-996a-46f02ef975b9.png)

使用内置quickfix插件没有出现问题。

可能是我没有设置好，请教一下解决方法，谢谢。

**Comment by skywind3000** [comment]
因为后台任务运行的目录是你的项目目录，而 Vim 的当前目录可能在其他地方，所以 cargo 输出的针对它自己的相对路径，Vim 当然会无法识别，解决方法有两个：

- 运行该任务时，将 Vim 的当前目录也 cd 到他的项目根目录那里，保持一致。
- 配置一下，让 cargo/rustc 输出绝对路径，这样你 vim 当前目录在哪里都无所谓。

**Comment by niuiic** [comment]
当前目录确实是在项目根目录下，这个没问题。事实上无论在A、B、C任何一个目录下都是不行的。

内置插件执行命令的时候是在进入vim之前的目录下，而不是在文件所在的目录下。查找文件的时候不是简单的根据相对路径来的，它借助了配置文件。可以说只要Cargo.toml写的没问题，随便在哪都找得到。

**Comment by niuiic** [comment]
顺便试了一下。哪怕只有main.rs也是不行的。依旧打开了一个空白文件。

![image](https://user-images.githubusercontent.com/63799565/112937870-0bbe3b80-915b-11eb-9429-598215ecd9ec.png)

**Comment by niuiic** [comment]
看tab上的显示，猜测可能是把前面的-->也当成文件名了，这有办法吗？

**Comment by niuiic** [comment]
在.task中注释掉下面一行可以解决问题

errorformat=%f:%l:%m

不过vim的当前目录也只能是项目根目录

另外这样的话没有显示warning和error以及错误位置，不仔细看的话看不出来是警告还是错误。
