### ISSUE TITLE
background job is still running 疑似卡死

### ISSUE THREAD

**Issue by niuiic** [skywind3000/asynctasks.vim#64]
写了一个build.sh，包含以下命令。使用插件运行该脚本，不知为何一直处于运行状态。在终端执行以下命令，很快就可以完成，猜测已被卡死。

```
ssh niuiic@192.168.1.108 "cd ~/AscendProjects/samples/cplusplus/level2_simple_inference/n_performance/1_multi_process_thread/face_recognition_camera && ./make.sh" > ./build.log 2>&1
sed -i "s/\/home\/niuiic\/AscendProjects\/samples\/cplusplus\/level2_simple_inference\/n_performance\/1_multi_process_thread\/face_recognition_camera/\/home\/niuiic\/Documents\/Project\/Cpp\/face_recognition/g" ./build.log
cat ./build.log
```

ssh已经设置免密码登陆，理论上不会导致卡住（内置的quickfix插件执行该脚本一切正常）。去掉这个ssh之后，确实不再卡住，但卡死原因不明。

另外quickfix窗口没有正常输出。只有以下内容。

![image](https://user-images.githubusercontent.com/63799565/115045994-95b32600-9f09-11eb-9927-6fdc0cc34bcf.png)

对于这点进行了以下测试。执行`ls -a`时输出正常，执行`cat xxx/build.log`（使用绝对路径或者相对路径）无输出。执行`:AsyncRun cat xxx/build.log`（使用绝对路径或者相对路径）无输出。不知这里有什么限制。

**Comment by niuiic** [comment]
问题已解决

**Comment by zhuoqun-chen** [comment]
> 问题已解决

请问是怎么解决的呢？我用ssh也出现了同样的报错，一直显示background job is still running
