### ISSUE TITLE
The ability to run last task

### ISSUE THREAD

**Issue by Shatur** [skywind3000/asynctasks.vim#65]
Is it possible to rerun last launched task as in VSCode?
![изображение](https://user-images.githubusercontent.com/22453358/115091149-67404580-9f1f-11eb-981f-d16bcf08b1d8.png)

**Comment by skywind3000** [comment]
https://github.com/skywind3000/asynctasks.vim/commit/7a8fddf0dd0cbe12c1860a2bc02debae4c300383

以支持，命令：

    :AsyncTaskLast

**Comment by Shatur** [comment]
Thanks!
