### ISSUE TITLE
能否添加脚本路径，支持通过task运行sh脚本或者py脚本等等

### ISSUE THREAD

**Issue by ZhiyuanLck** [skywind3000/asynctasks.vim#7]

**Comment by skywind3000** [comment]
有一个相对于脚本路径的变量：

**Comment by ZhiyuanLck** [comment]
嗯，我表达不太清楚，是能否添加一个脚本工作目录存放自定义的脚本，然后可以通过task很方便的调用脚本实现较为复杂的功能，而不是原来的一行命令，虽然脚本也可以写成一行，但是有时候太长了

**Comment by ZhiyuanLck** [comment]
好的，谢谢！

**Comment by ZhiyuanLck** [comment]
AsyncTaskMacro里还没有更新这两个宏

**Comment by skywind3000** [comment]
因为不同任务来自不同配置文件，这两个值不同，没法写一个统一的。
