### ISSUE TITLE
No tasks output

### ISSUE THREAD

**Issue by Balrrach** [skywind3000/asynctasks.vim#75]
Good afternoon. I'm trying to use asynctasks with neovim, particularly with the gui lunarvim.
I'm not able to get any kind of output from any task no matter what options I select. An example of task is:
```
[project-build]
command=cd build && cmake ..
cwd=<root>
output=quickfix
errorformat=%f:%l:%m
```
The task does what it should do but as said no output is produced. Tasks that fail don't produce any output either.

**Comment by skywind3000** [comment]
:copen 6

**Comment by Balrrach** [comment]
Yes, my bad, sorry. Thanks for your time.
