### ISSUE TITLE
能不能关闭output quickfix

### ISSUE THREAD

**Issue by Leiyi548** [skywind3000/asynctasks.vim#80]
![image](https://user-images.githubusercontent.com/76139422/148537621-e7a255da-4c40-419b-a58e-615eb4522247.png)
我只是想要打开外部东西不想要有输出显示
![image](https://user-images.githubusercontent.com/76139422/148538190-80c058b9-5727-42df-b55c-d151975afd00.png)

**Comment by skywind3000** [comment]
看文档，设置

output=terminal
pos=hide
