### ISSUE TITLE
Expose last_task as global variable

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [skywind3000/asynctasks.vim#89]
I would like to have the last run task in my statusline. The `s:last_task` is a script-local variable. Is there anyway to achieve this?

If not, would you accept a PR for this?

**Comment by skywind3000** [comment]
please update to the latest version, a new variable `g:asynctasks_last` is introduced for this.

**Comment by KaiHoewelmeyer-TomTom** [comment]
Wow. That was a quick fix. Thank you so much! I will test it.

**Comment by KaiHoewelmeyer-TomTom** [comment]
Works great and as expected. Once more: Thank you!
