### ISSUE TITLE
[Suggestion] fzf-lua example for wiki

### ISSUE THREAD

**Issue by deathmaz** [skywind3000/asynctasks.vim#95]
Hi, thank you very much for a nice plugin. I made an example on how to integrate [fzf-lua](https://github.com/ibhagwan/fzf-lua) as a UI for asynctasks, which might be useful to have in wiki along side with examples of other fuzzy finders. Please let me know if there's a way that I can add this to wiki by my own. It also should be mentioned in [docs](https://github.com/skywind3000/asynctasks.vim/blob/master/doc/asynctasks.txt#L565) i think. But again I don't know what the workflow is to properly add it both to docs and to wiki.

![image](https://user-images.githubusercontent.com/6440135/184432682-9dd8663b-00d5-45f5-8eb9-55a06d2c3cdb.png)

```lua
local fzf_lua = require('fzf-lua')
vim.keymap.set('n', '\\t',
  function()
    local rows = vim.fn['asynctasks#source'](vim.go.columns * 48 / 100)
    fzf_lua.fzf_exec(function(cb)
      for _, e in ipairs(rows) do
        local color = fzf_lua.utils.ansi_codes
        local line = color.green(e[1]) .. ' ' .. color.cyan(e[2]) .. ': ' .. color.yellow(e[3])
        cb(line)
      end
      cb()
    end,
      {
        actions = {
          ['default'] = function(selected)
            local str = fzf_lua.utils.strsplit(selected[1], ' ')
            local command = 'AsyncTask ' .. vim.fn.fnameescape(str[1]);
            vim.api.nvim_exec(command, false)
          end
        },
        fzf_opts = {
          ["--no-multi"] = '',
          ["--nth"]      = '1',
        },
        winopts = {
          height = 0.6,
          width = 0.6,
        }
      })
  end,
  { noremap = true, silent = true })
```

**Comment by skywind3000** [comment]
https://github.com/skywind3000/asynctasks.vim/wiki/UI-Integration

updated

**Comment by skywind3000** [comment]
Maybe you can create a plugin like:

https://github.com/GustavoKatel/telescope-asynctasks.nvim 

I will list it in the README.md

**Comment by deathmaz** [comment]
Thank you I'll try. Will let you know when it's ready

**Comment by deathmaz** [comment]
> Maybe you can create a plugin like:
> 
> https://github.com/GustavoKatel/telescope-asynctasks.nvim
> 
> I will list it in the README.md

@skywind3000 https://github.com/deathmaz/fzf-lua-asynctasks

**Comment by skywind3000** [comment]
listed:

https://github.com/skywind3000/asynctasks.vim#extensions
