### ISSUE TITLE
诸如 VIM_FILEPATH 在 neovim 下的支持问题

### ISSUE THREAD

**Issue by QiangZiBro** [skywind3000/asynctasks.vim#97]
Hello，想问诸如 VIM_FILEPATH 变量在 neovim 下是否不支持？如下是运行时的报错
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/30493365/197398741-d99008a4-047a-4454-8508-83f4fd70104f.png">

NVIM v0.8.0-dev-969-g7a9b59379

**Comment by skywind3000** [comment]
你用什么命令启动的？

**Comment by QiangZiBro** [comment]
> 你用什么命令启动的？

F5 键实际运行的命令：
exec 'FloatermNew --autoclose=0 --cwd=<buffer>' cmd

python 文件， cmd 为
let cmd = 'python3 "$(VIM_FILEPATH)"'

**Comment by skywind3000** [comment]
那你是用的 Floaterm 啊，又不是 AsyncRun，它不解析这些宏，请用：

exec 'AsyncRun -mode=terminal -pos=floaterm ' . cmd
